version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    environment:
      - MYSQL_HOST=mysql-container
      - REDIS_HOST=redis-container
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app

volumes:
  mysql_data:
  redis_data:
